on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world public action step
        uses: vitorsouza23/test-my-git-action@v1.1
        id: hello
        with:
          who-to-greet: "Ta segurando a corda Genivaldo?"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
